---
title: "TLKnotes_02_gitFishREACalcWD"
output: html_document
---

#####LOAD PACKAGES, FUNCTIONS, AND DATA
```{r message = FALSE, warning = FALSE}
rm(list=ls())
library(gdata)             # needed for drop_levels()
library(reshape)           # reshape library inclues the cast() function used below

#LOAD LIBRARY FUNCTIONS
source("lib/core_functions.R")
source("lib/fish_team_functions.R")

#LOAD THE CLEAN WORKING DATASET 
load("TMPwd.Rdata")
```


#####FINAL CLEANING OF DATASET
```{r message = FALSE, warning = FALSE}
##FILTER DATA TYPES: I = instantaneous; N = non-instantaneous; F = new species seen during 5-10 min window of survey; T = new species seen during 10-30 min window of survey; P = presence (outside cylinder, species of interest)

#Historical info about SPC design/data types: 
#Initially, didn't record I vs. N, so all observations were labelled as U = unidentified; **pool U, I, N data for abundance/biomass calcs! 
#In late 2012, started recording F and T in an effort to record more piscivores and lg. parrots **haphazardly/opportunistically done up until ~2017, so DON'T use prior to recent surveys
# (as of 2019, have only used F and T data in recent rebreather comparison study)
#P = binary presence/absence data: don't include in abundance/biomass calcs; have used P data for specific species of interest (e.g. humpheads, sharks, etc.) for stock assessments (Mark Nadon)

wd[!wd$OBS_TYPE %in% c("U", "I", "N"), ]$COUNT<-0  #turn all other unwanted data types to 0, so indiv. site isn't dropped altogether if other types of observations were collected there

##FILTER SURVEY METHOD: 
wd<-subset(wd, wd$METHOD %in% c("nSPC")) #keep nSPC method only
wd<-droplevels(wd) #drop unused levels

##DEFINE SURVEY IDENTIFIERS 
UNIQUE_SURVEY<-c("SITEVISITID","METHOD")
UNIQUE_REP<-c(UNIQUE_SURVEY, "REP")
UNIQUE_COUNT<-c(UNIQUE_REP, "REPLICATEID")

##ASSIGN/CALCULATE SURVEY METADATA
SURVEY_INFO<-c("OBS_YEAR", "REGION", "REGION_NAME", "ISLAND", "ANALYSIS_SCHEME", "ANALYSIS_YEAR", "SEC_NAME", "SITE", "DATE_", "REEF_ZONE", "DEPTH_BIN", "LATITUDE", "LONGITUDE", "SITEVISITID", "METHOD")
survey_table<-Aggregate_InputTable(wd, SURVEY_INFO)

OTHER_BENTHIC<-c("CLAM", "CORALLIMORPH", "ZOANTHID", "TUNICATE", "SPONGE", "TA", "CYANO", "OTHER", "SOFT_CORAL") #used to collect all these categories individually --> pool into "OTHER_BENTHIC" to match our current methods where all these categories would be part of our "OTHER" category
wd$OTHER_BENTHIC<-rowSums(wd[,OTHER_BENTHIC], na.rm=T) #sum estimates of OTHER_BENTHIC
SURVEY_SITE_DATA<-c("DEPTH", "HARD_CORAL", "MA", "CCA", "SAND", "OTHER_BENTHIC", "ComplexityValue", "MEAN_SH", "SD_SH_DIFF", "MAX_HEIGHT")

##FORM DATAFRAME OF SITE METADATA AND BENTHIC ESTIMATES FOR EACH SURVEY
#calculate % cover estimates based on diver visual estimates --> **Use only if we have NO PHOTOQUAD DATA for an area!!
survey_est_benthos<-Calc_Site_nSurveysArea(wd, UNIQUE_SURVEY, UNIQUE_REP, UNIQUE_COUNT, SURVEY_SITE_DATA)  #Calc_Site_nSurveysArea function deals better with situations where one REP has benthic data and the other doesnt 
surveys<-merge(survey_table, survey_est_benthos, by=UNIQUE_SURVEY)
save(surveys, file="TMPsurveys.Rdata")

##FORM DATAFRAME OF FISH SPECIES INFO (for possible later use)
FISH_SPECIES_FIELDS<-c("SPECIES","TAXONNAME", "FAMILY", "COMMONFAMILYALL", "TROPHIC_MONREP", "LW_A", "LW_B", "LENGTH_CONVERSION_FACTOR")
species_table<-Aggregate_InputTable(wd, FISH_SPECIES_FIELDS)
save(species_table, file="TMPspecies.Rdata")
```


#####CALCULATE SUMMARY METRICS PER SITE --> Refer to fish_team_functions script for clarification and potential tweaks!
```{r message = FALSE, warning = FALSE}
##examples:
r1<-Calc_Site_Bio(wd, "TROPHIC_MONREP"); trophic.cols<-names(r1[3:dim(r1)[2]])
r2a<-Calc_Site_Abund(wd, "SPECIES"); species.cols<-levels(species_table$SPECIES)
r2b<-Calc_Site_Bio(wd, "SPECIES"); species.cols<-levels(species_table$SPECIES)
r3<-Calc_Site_Bio_By_SizeClass(wd, c(0,20,50,Inf)); size.cols<-names(r4b)[3:dim(r4b)[2]]
r4<-Modified_Site_Species_Richness(wd)
r5<-Calc_Site_MeanLength(wd,min_size=0.4) 

##merge site metadata/benthic estimates and summary metrics calculated above per site and grouping variable (e.g. Species, Tropic_MonRep, Family) 
#examples:
wsd<-merge(surveys,r1,by=UNIQUE_SURVEY)
wsd$TotFish<-rowSums(wsd[,trophic.cols]) #sum across all fishes 
data.cols<-c(trophic.cols, "TotFish", SURVEY_SITE_DATA) #**Ivor keeps track of column names as he builds up dataset (don't have to do it here!), but need data.cols for pooling up!
wsd<-merge(wsd, r3, by=UNIQUE_SURVEY)
data.cols<-c(data.cols, "0_20", "20_50", "50_plus")
names(wsd)[match(c("(0,20]", "(20,50]","(50,Inf]" ),names(wsd))] <- c("0_20", "20_50", "50_plus") #rename columns of size classes

##calculate BSR per site: BSR = benthic substrate ratio (this was for a specific analysis)
wsd$BSR<-(wsd$HARD_CORAL+wsd$CCA)/(100-wsd$HARD_CORAL+wsd$CCA)  
```


#####SAVE DATASET (SITE-LEVEL DATA)
```{r message = FALSE, warning = FALSE}
save(wsd, file="TMPwsd.Rdata") #wsd = working site data
save(data.cols, file="TMPdata.cols.Rdata")


##CAPPING OF DATA: because right-skewing of data can greatly influence estimates, can cap data (e.g., 95th percentile). Think about potentially capping within a region?
# **Code currently caps all data combined (Pacific-wide)
#Have capped data in PRIMNM Monitoring Report (avoids giant bubbles in bubble plots), Mary and Adel have done it, Ivor has never done it


#display quantile ranges of the data.cols
for(i in 1:(length(data.cols)))
{
	cat(data.cols[i]); 	cat(" ")
	cat(round(quantile(wsd[,data.cols[i]], c(0.9,0.95,0.975, 0.99), na.rm = T),1)); 	cat("      ") #look at the percentiles
}

#CAP FISH DATA VALUES TO SOMETHING CLOSE To 97.5% quantile <-- KAYLYN MCCOY TWEAKED CODE FOR PRIMNM REPORT
wsd[wsd$TotFish>450,]$TotFish<-450
wsd[wsd$PISCIVORE>300,]$PISCIVORE<-300
wsd[wsd$PLANKTIVORE>100,]$PLANKTIVORE<-100 # KM changed from 50
wsd[wsd$PRIMARY>80,]$PRIMARY<-80 # KM changed from 85
wsd[wsd$SECONDARY>45,]$SECONDARY<-45 # KM changed from 40

#CAP BSR: can be infinite in situations where divers record TA and MA as 0 (rare, but does happen) 
wsd[wsd$BSR>25 & !is.na(wsd$BSR),]$BSR<-25   #IDW - even 25 is super high!

#SAVE CAPPED DATASET
save(wsd, file="TMPwsdCAPPED.rdata")
```



