---
title: "TLKnotes_03_gitFishREAPoolData"
output: html_document
---

#####LOAD PACKAGES, FUNCTIONS, AND DATA
```{r message = FALSE, warning = FALSE}
rm(list=ls())
library(gdata)             # needed for drop_levels()
library(reshape)           # reshape library inclues the cast() function used below

#LOAD LIBRARY FUNCTIONS
source("lib/core_functions.R")
source("lib/fish_team_functions.R")
source("lib/Islandwide Mean&Variance Functions.R")

#LOAD THE CLEAN wsd and sectors data
load("TMPsectors.Rdata")
load("TMPwsd.Rdata")
load("TMPdata.cols.Rdata")
```


#####FINAL DATA CLEANING, PREP FOR POOLING 
```{r message = FALSE, warning = FALSE}
##CHECK FOR ISLANDS THAT AREN'T IN SECTORS FILE 
setdiff(unique(wsd$ISLAND),unique(sectors$ISLAND))

##ADJUST DEPTH_BINs 
#could leave depths if interested in, e.g., backreef of a specific island. **Note: often run into low sampling issues!
levels(wsd$DEPTH_BIN)<-c(levels(wsd$DEPTH_BIN), "All")
wsd[wsd$REEF_ZONE=="Backreef",]$DEPTH_BIN<-"All" #set backreef zones to "All" (site-level data)
sectors[sectors$REEF_ZONE=="Backreef",]$DEPTH_BIN<-"All" #set backreef zones to "All" (sectors metadata)

wsd$DEPTH_BIN<-as.character(wsd$DEPTH_BIN) #won't change value to "All" if it is a factor
wsd[wsd$ISLAND=="Rose" & wsd$REEF_ZONE=="Lagoon",]$DEPTH_BIN<-"All" #set lagoon at Rose to "All" (site-level data)
sectors[sectors$ISLAND=="Rose" & sectors$REEF_ZONE=="Lagoon",]$DEPTH_BIN<-"All" #set lagoon at Rose to "All" (sector metadata)
wsd$DEPTH_BIN<-as.factor(wsd$DEPTH_BIN) #change DEPTH_BIN back to a factor

##ASSIGN STRATA = reef zone + depth
wsd$STRATA<-paste(substring(wsd$REEF_ZONE,1,1), substring(wsd$DEPTH_BIN,1,1), sep="") #site-level data
sectors$STRATA<-paste(substring(sectors$REEF_ZONE,1,1), substring(sectors$DEPTH_BIN,1,1), sep="") #sector metadata

##COMBINE GUGUAN, ALAMAGAN, AND SARIGAN AS ONE ISLAND: only go to each island for 1 day (each island is a sector!) 
#technically, they are one base reporting unit, but simpler to make them one "ISLAND"
### TLK: AS OF NOW, THIS CODE ONLY CHANGES NAMES TO POOL ISLANDS INTO ONE ISLAND GROUPING (SECTORS STILL KEEP EACH ISLAND AS AN INDIV SECTOR)
##        *decide based on sample size if need to pool into one sector, island, etc.
SGA<-c("Guguan", "Alamagan", "Sarigan")
levels(wsd$ISLAND)<-c(levels(wsd$ISLAND), "AGS")
wsd[wsd$ISLAND %in% SGA,]$ISLAND<-"AGS"
sectors[sectors$ISLAND %in% SGA,]$ISLAND<-"AGS"

##COMBINE REEF-FISH CRUISES IN HAWAII AS ONE "YEAR" 
#supplemental reef fish cruises were conducted in Hawaii to fill in gaps and survey places we don't go otherwise --> not comparable areas of islands within a given cruise/year, so best to pool them as one "year" 
levels(wsd$ANALYSIS_YEAR)<-c(levels(wsd$ANALYSIS_YEAR), "2016on")
wsd[wsd$REGION %in% c("MHI", "NWHI") & wsd$OBS_YEAR==2016,]$ANALYSIS_YEAR<-"2016on"
wsd[wsd$REGION %in% c("MHI", "NWHI") & wsd$OBS_YEAR %in% seq(2010,2012),]$ANALYSIS_YEAR<-"2010-12"
wsd[wsd$REGION %in% c("MHI", "NWHI") & wsd$OBS_YEAR %in% seq(2013,2015),]$ANALYSIS_YEAR<-"2013-15"
```


#####BUILD TABLE OF ALL ANALYSIS STRATA AND THEIR SIZES
```{r message = FALSE, warning = FALSE}
#Turn sector and analysis scheme into analyses_sec (sector used for analyses per analysis_scheme) and calculate size of sector
SCHEMES<-c("RAMP_CURRENT", "RAMP_BASIC", "MARI2011", "MARI2014", "TUT10_12", "AS_SANCTUARY") #include all analysis schemes as possibilities
for(i in 1:length(SCHEMES)){
	tmp2<-sectors[,c("SEC_NAME", SCHEMES[i])]
	tmp2$SCHEME<-SCHEMES[i]
	names(tmp2)<- c("SEC_NAME", "ANALYSIS_SEC", "ANALYSIS_SCHEME")
	
	tmp<-aggregate(sectors$AREA_HA, sectors[,c(SCHEMES[i], "STRATA")], sum)
	tmp$SCHEME<-SCHEMES[i]
	names(tmp)<-c("ANALYSIS_SEC", "STRATA", "AREA_HA", "ANALYSIS_SCHEME")
	if(i==1){
		st<-tmp
		as<-tmp2
	} else {
		st<-rbind(st, tmp) 
		as<-rbind(as, tmp2)
	}	
}

as$TMP<-1
as<-aggregate(as$TMP, by=as[,c("SEC_NAME", "ANALYSIS_SCHEME", "ANALYSIS_SEC")], length) 
as$x<-NULL

##ANALYSIS_SCHEMES = grouping of sectors based on sampling effort per year
#current code: applies each year's assigned analysis scheme to year-region 
#could write code to apply only 1 scheme for analysis of a specific area (e.g., use smallest scale/finest grained spatial scheme of an island for temporal analysis?)

wsd<-merge(wsd, as, by=c("SEC_NAME", "ANALYSIS_SCHEME"), all.x=T)  #add ANALYSIS_SCHEME to sector-scheme combinations
unique(wsd[is.na(wsd$ANALYSIS_SCHEME), c("ISLAND", "ANALYSIS_SEC", "SEC_NAME", "OBS_YEAR", "ANALYSIS_YEAR", "ANALYSIS_SCHEME", "STRATA")])
cast(st, ANALYSIS_SEC ~ ANALYSIS_SCHEME, value="AREA_HA", sum) #table of sector sizes across analysis schemes --> visual check if anything looks weird
#check if any are missing an AREA_HA (didn't get into the stratification scheme properly); **CAN'T have missing AREA_HA values
#there is one site (FFS lagoon-deep doesn't exist) --> **fix in Oracle Database, drop, or change to lagoon-mid to continue!
wsd<-merge(wsd, st, by=c("ANALYSIS_SCHEME", "ANALYSIS_SEC", "STRATA"), all.x=T)
unique(wsd[is.na(wsd$AREA_HA), c("ISLAND", "ANALYSIS_SEC", "SEC_NAME", "OBS_YEAR", "ANALYSIS_YEAR", "ANALYSIS_SCHEME", "STRATA")]) 

##CHECK # OF REPS PER STRATA: need a minimum of 2 reps per strata (=default cutoff, strata dropped in code in section below)
#B = backreef, F=forereef, P = protected slope, L = lagoon
a<-cast(wsd, REGION + ANALYSIS_SCHEME + ISLAND + ANALYSIS_SEC + ANALYSIS_YEAR ~ STRATA, value="AREA_HA", length); a

##SAVE TABLE OF # OF SITES PER YEAR (for specific project)
save(a, file="sites_year_reef_zone_depth_bin.rdata") 
```


#####POOL WSD (SITE --> STRATA --> LARGER SPATIAL SCALES)
```{r message = FALSE, warning = FALSE}
##Calculate mean and variance within strata
SPATIAL_POOLING_BASE<-c("REGION", "ISLAND", "ANALYSIS_SEC", "REEF_ZONE", "STRATA") #spatial properties to pool data by   
ADDITIONAL_POOLING_BY<-c("METHOD", "ANALYSIS_YEAR")  #additional fields to pool data by, but which do not relate to physical/spatial properties (e.g., survey year or method)

#Generate within-strata means and variances
POOLING_LEVEL<-c(SPATIAL_POOLING_BASE, ADDITIONAL_POOLING_BY) #desired pooling
dps<-Calc_PerStrata(wsd, data.cols, c(POOLING_LEVEL, "AREA_HA")) #calculate per strata
#save(dps,file="tmp REA per strata.RData") #save strata estimates
#head(dps$Mean)

##Keep strata with N>1 (cannot pool up strata with N<1)
dps$Mean<-dps$Mean[dps$Mean$N>1,]
dps$SampleVar<-dps$SampleVar[dps$SampleVar$N>1,]
dps$SampleSE<-dps$SampleSE[dps$SampleSE$N>1,]

##Pool to higher levels of interest
#some examples of pooling:  
# e.g. BY ISLAND AND REEF_ZONE PER YEAR
OUTPUT_LEVEL<-c("REGION", "ISLAND", "REEF_ZONE", "ANALYSIS_YEAR") 
dp<-Calc_Pooled_Simple(dps$Mean, dps$SampleVar, data.cols, OUTPUT_LEVEL, "AREA_HA")
save(dp, file="data_pooled_is_yr_RZ.Rdata")

# e.g. BY ISLAND PER YEAR
OUTPUT_LEVEL<-c("REGION","ISLAND", "ANALYSIS_YEAR", "METHOD")
dp<-Calc_Pooled_Simple(dps$Mean, dps$SampleVar, data.cols, OUTPUT_LEVEL, "AREA_HA")
save(dp, file="data_pooled_is_yr.Rdata")

# e.g. BY ISLAND POOLING ALL YEARS' DATA
OUTPUT_LEVEL<-c("REGION","ISLAND", "METHOD")
dp<-Calc_Pooled_Simple(dps$Mean, dps$SampleVar, data.cols, OUTPUT_LEVEL, "AREA_HA")
save(dp, file="data_pooled_is.Rdata")

# e.g. BY ISLAND AND SECTOR PER YEAR
OUTPUT_LEVEL<-c("REGION","ISLAND", "ANALYSIS_SEC", "ANALYSIS_YEAR", "METHOD")
dp<-Calc_Pooled_Simple(dps$Mean, dps$SampleVar, data.cols, OUTPUT_LEVEL, "AREA_HA")
save(dp, file="data_pooled_SEC_yr.Rdata")

# e.g. BY REGION PER YEAR
OUTPUT_LEVEL<-c("REGION", "ANALYSIS_YEAR", "METHOD") 
dp<-Calc_Pooled_Simple(dps$Mean, dps$SampleVar, data.cols, OUTPUT_LEVEL, "AREA_HA")
save(dp, file="MONREPdata_pooled_reg.rdata")
```

